theme: jekyll-theme-minimal
title: The Tale of the Unfinished Paths 
description: An analysis on the manifestation of unfinished paths driving the players to quit the Wikispeedia game.
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: 1. Between game
    url: between_game
  - title: 2. In game
    url: in_game
  - title: 3. Classification
    url: classification
  - title: 4. Conclusion
    url: conclusion
